export const SEARCH_FOCUS='header/SEARCH_FOCUS'
export const SEARCH_BLUR='header/SEARCH_BLUR'
export const CHANGE_LIST='header/CHANGE_LIST'
export const MOUSE_IN='header/MOUSE_IN'
export const mouse_Leave='header/mouse_Leave'
export const change_Page='header/change_Page'
